### ISSUE TITLE
Potential high-priority security issue

### ISSUE THREAD

**Issue by ghost** [NeverDecaf/discord-userscripts#2]
Hello, I will be brief: There may be a security concern in this repo affecting you specifically between lines 31 and 37 of the js file.

I believe if you want to remove this from your GitHub history you can delete the repo and re-publish it. I would consider that if I were in your place.

**Comment by NeverDecaf** [comment]
Thanks for the warning, however this is a dummy account used by [BetterDiscord](https://github.com/rauenzi/BetterDiscordApp) which you can find [here in the source](https://github.com/rauenzi/BetterDiscordApp/blob/fd43ebf7b8f0a19c2f9a6d7b3204e951e5a2697e/renderer/src/modules/webpackmodules.js) so I assume it's fine to leak this secret.
